config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  resources :users do
    resources :favourites
    resources :watches, :path => "watched"     
  end

  get '/movies/christmas/', to: 'movies#christmas'
  get '/movies/related/:id', to: 'movies#related'
  get '/movies/rt/:id', to: 'movies#rt'
  get '/movies/traileraddict/:id', to: 'movies#traileraddict'

  get 'movies/refresh'
  get 'movies/reddit'
  get 'info/registrations'

  get 'home/trakt'

  # Tests
  get 'home/reddit'
  get 'home/apiRTMovieTest'
  get 'home/apiRTTest'
  get 'home/apitest2'
  get 'home/apitest'

  resources :movies

  # match 'users/sign_up', to: 'info#registrations', via: [:get, :post]

  

  root 'movies#index'

end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  before_filter :authenticate_user!, only: [:new, :edit, :update, :destroy, :refresh, :create]
  before_action :set_movie, only: [:show, :edit, :update, :destroy, :related, :reddit, :rt, :traileraddict]

  # GET /movies
  # GET /movies.json
  def index
    per_page = (params.has_key?(:per_page) && params[:per_page].to_i != 0) ? params[:per_page].to_i : 24
    @movies = Movie.joins(:trending).all.page(params[:page]).per_page(per_page)
    @include_header = true
  end

  # GET /movies/1
  # GET /movies/1.json
  def show
    @userID = (current_user.blank?) ? 0 : current_user.id
    @isUserFavourite = Favourite.where(user_id: @userID, movie_id: @movie.id).count > 0 ? true : false
  end

  def rt
    @rt_critic_reviews = Feed.get_feeds(movie: @movie, site: 'rotten_tomatoes', clear_cache: :true)  
  end

  def traileraddict
    @traileraddict = Feed.get_feeds(movie: @movie, site: 'trailer_addict', clear_cache: :true)  
  end

  def reddit
    @reddit = Feed.get_feeds(movie: @movie, site: 'reddit', clear_cache: :true)
  end

  def related
    @relatedMovies = Movie.related(movie: @movie)
  end

  # GET /movies/new
  def new
    @movie = Movie.new
  end

  # GET /movies/1/edit
  def edit
  end

  # GET /movies/refresh - trending videos
  def refresh    
    @result, @processedMovies, @errors = Movie.refresh_listings
  end

  # POST /movies
  # POST /movies.json
  def create
    @movie = Movie.new(movie_params)

    respond_to do |format|
      if @movie.save
        format.html { redirect_to @movie, notice: 'Movie was successfully created.' }
        format.json { render :show, status: :created, location: @movie }
      else
        format.html { render :new }
        format.json { render json: @movie.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /movies/1
  # PATCH/PUT /movies/1.json
  def update
    respond_to do |format|
      if @movie.update(movie_params)
        format.html { redirect_to @movie, notice: 'Movie was successfully updated.' }
        format.json { render :show, status: :ok, location: @movie }
      else
        format.html { render :edit }
        format.json { render json: @movie.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /movies/1
  # DELETE /movies/1.json
  def destroy
    @movie.destroy
    respond_to do |format|
      format.html { redirect_to movies_url, notice: 'Movie was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_movie
      @movie = Movie.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def movie_params
      params.require(:movie).permit(:title, :year, :released, :url, :trailer, :runtime, :tagline, :certification, :imdb_id, :tmdb_id, :poster, :watchers)
    end

end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/views/movies/_form.html.erb
<%= form_for(@movie) do |f| %>
  <% if @movie.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@movie.errors.count, "error") %> prohibited this movie from being saved:</h2>

      <ul>
      <% @movie.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :year %><br>
    <%= f.number_field :year %>
  </div>
  <div class="field">
    <%= f.label :released %><br>
    <%= f.number_field :released %>
  </div>
  <div class="field">
    <%= f.label :url %><br>
    <%= f.text_field :url %>
  </div>
  <div class="field">
    <%= f.label :trailer %><br>
    <%= f.text_field :trailer %>
  </div>
  <div class="field">
    <%= f.label :runtime %><br>
    <%= f.number_field :runtime %>
  </div>
  <div class="field">
    <%= f.label :tagline %><br>
    <%= f.text_field :tagline %>
  </div>
  <div class="field">
    <%= f.label :certification %><br>
    <%= f.text_field :certification %>
  </div>
  <div class="field">
    <%= f.label :imdb_id %><br>
    <%= f.text_field :imdb_id %>
  </div>
  <div class="field">
    <%= f.label :tmdb_id %><br>
    <%= f.text_field :tmdb_id %>
  </div>
  <div class="field">
    <%= f.label :poster %><br>
    <%= f.text_field :poster %>
  </div>
  <div class="field">
    <%= f.label :watchers %><br>
    <%= f.number_field :watchers %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/movies/edit.html.erb
<h1>Editing movie</h1>

<%= render 'form' %>

<%= link_to 'Show', @movie %> |
<%= link_to 'Back', movies_path %>

app/views/movies/index.html.erb
<ol class="breadcrumb">
  <li class="active">Trending Movies</li>
</ol>

<div class="row">

  <% @movies.each_with_index do |movie,index| %>

    <!-- Movie: Container -->
    <div class="grid col-lg-2 col-md-3 col-sm-4 col-xs-6 movie js-movie-item js-movie-item-<%= movie.id %>" data-movie-id="<%= movie.id %>">
      
      <!-- Poster -->
      <figure class="effect-apollo movie-poster js-movie-poster">
        <%= image_tag(movie.posterThumbnailURL, size: "138x197", alt: truncate(movie.title, length: 22) + ' Poster', class: 'img-responsive') %>
        <figcaption>
          <p>Click for more info</p>
        </figcaption>     
      </figure>

      <!-- Movie: Title -->
      <div class="col-md-12 movie-title">
        <small><%= truncate(movie.title, length: 22) %></small>
      </div>

    </div>

    <!-- Row seperators for different resolutions -->
    <% if (index + 1) % 6 == 0 %>
       <!-- Large Movie Info -->
      <div class="col-lg-12 visible-lg-block js-movie-info-container js-movie-info-container-lg"></div>
    <% end %>

    <% if (index + 1) % 4 == 0 %>
       <!-- Medium Movie Info -->
      <div class="col-md-12 visible-md-block js-movie-info-container js-movie-info-container-md"></div>
    <% end %>

    <% if (index + 1) % 3 == 0 %>
       <!-- Small Movie Info -->
      <div class="col-sm-12 visible-sm-block visible-sm-block js-movie-info-container js-movie-info-container-sm"></div>
    <% end %>

    <% if (index + 1) % 2 == 0 %>
       <!-- XS Movie Info -->
      <div class="col-xs-12 visible-xs-block js-movie-info-container js-movie-info-container-xs"></div>
    <% end %>


  <% end %>
</div>

<div class="row text-center">
  <%= will_paginate @movies,previous_label: h("<"), next_label: h(">"), renderer: BootstrapPagination::Rails %>  
</div>

app/views/movies/new.html.erb
<h1>New movie</h1>

<%= render 'form' %>

<%= link_to 'Back', movies_path %>

app/views/movies/refresh.html.erb
<h1>Movie Refresh</h1>

<h4>API Fetch Result:</h4>
<%= @result %>

<!-- Errors -->
<% if @errors.count > 0 %>
	<h2>Errors</h2>
	<ul>
		<% @errors.each do |error| %>
			<li><%= error %></li>
		<% end %>
	</ul>
<% end %>

<!-- Processed Files -->
<h2>Processed Movies</h2>
<% if @processedMovies.count > 0 %>
	<ul>
		<% @processedMovies.each do |movieTitle| %>
			<li><%= movieTitle %></li>
		<% end %>
	</ul>
<% else %>
	<p>No movies processed</p>
<% end %>

app/views/movies/related.html.erb
<ol class="breadcrumb">
  <li><%= link_to 'Trending Movies', movies_path %></li>
  <li><%= link_to @movie.title, @movie %></li>
  <li class="active">Related Movies</li>
</ol>

<p>Recommendations based on <em><%= @movie.title %></em>:<p>

<div class="list-group">

  <% @relatedMovies.each do |movie| %>
    <%= link_to movie, class: 'list-group-item row' do %>
      <div class='col-sm-2'>
        <%= image_tag movie.posterSmallURL, width: '64', class: 'img-responsive' %>
      </div>

      <div class='col-sm-10'>
        <h4 class="list-group-item-heading"><%= movie.title %></h4>
        <p class="list-group-item-text"><%= movie.overview %></p>
      </div>
      
    <% end %>
  <% end %>

</div>

app/views/movies/show.html.erb
<ol class="breadcrumb">
  <li><%= link_to 'Trending Movies', movies_path %></li>
  <li class="active"><%= @movie.title %></li>
</ol>

<style>
  .fanart-header:after {
    background-image: url(<%= @movie.fanartURL %>);
  }
</style>

<div class="row" style="margin-top:0">

  <div class="col-md-12">
    <div class="img-responsive">
      <div class="fanart-header">

        <div class="row">

          <!-- Left Side -->
          <div class="col-md-3">
            <%= image_tag(@movie.posterURL, size: "138x197", class: 'img-responsive poster', alt: @movie.title + ' Poster') %>
          </div>

          <!-- Right Side -->
          <div class="col-md-9">

            <h1 class='js-main-movie-title'><%= @movie.title %></h1>
            <h6><em><%= @movie.tagline %></em></h6>
            <p><%= @movie.overview %></p>

            <div class="pull-right quicklinks">
              <span class="label label-info hidden-sm hidden-xs">Released: <%= @movie.released_formatted %></span>
              <span class="label label-info">Rating: <%= @movie.certification %></span>
              <span class="label label-info hidden-xs">Runtime: <%= @movie.runtime %> mins</span>

              <% if @movie.imdb_id %>
                <span class="label label-info"><a href="http://www.imdb.com/title/<%= @movie.imdb_id %>">IMDB</a></span>
              <% end %>
              
              <% if @movie.trailer %>
                <span class="label label-info">
                  <a href="<%= @movie.trailer %>"><i class="fa fa-youtube">YouTube</i></a>
                </span>
              <% end %>

              <% if user_signed_in? %>
                <a class='js-add-to-favs btn btn-default btn-xs' style='margin-left:0.6em;' data-id="<%= @movie.id %>" data-userid="<%= current_user.id %>" href="#">Add To Favourites</a>
              <% end %>

              <!-- <a href="#" class="btn btn-default js-add-to-favs">Add To Favourites</a> -->

            </div>

          </div><!-- end col -->

        </div><!-- end row -->

          
      </div>
    </div>
  </div>

</div>

<div class="panel panel-success">

  <ul class="js-movie-tabs ticket-menu" role="tablist" data-movie-id="<%= @movie.id %>">

      <li>
        <a href="#Rotten-Tomatoes-Reviews"
             class='ticket-menu-item rotten-tomatoes text-hide'
             role="tab"
             data-toggle="tab">Rotten Tomatoes<sup>&copy;</sup> Reviews</a>
      </li>

      <li>
        <a class='js-default-tab ticket-menu-item similar text-hide'
             href="#recommendations"
             role="tab"
             data-toggle="tab">Similar</a></li>

      <li>
        <a href="#reddit"
           class='ticket-menu-item reddit text-hide'
           role="tab"
           data-toggle="tab">Reddit</a>
      </li>
      <li>
        <a href="#trailer-addict"
           class='ticket-menu-item cinema text-hide'
           role="tab"
           data-toggle="tab">Videos</a>
      </li>
    </ul>

</div>

<div class="row js-movie-contents">
  <div class="col-md-12">

    <!-- Tab panes -->
    <div class="tab-content">
      <div class="tab-pane" id="recommendations"></div>
      <div class="tab-pane active" id="Rotten-Tomatoes-Reviews"></div>
      <div class="tab-pane" id="reddit"></div>
      <div class="tab-pane" id="trailer-addict"></div>
    </div>
  </div>
</div>

<% if false %>
  <%= link_to 'Edit', edit_movie_path(@movie) %> |
  <%= link_to 'Back', movies_path %>
<% end %>