config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  resources :users do
    resources :favourites
    resources :watches, :path => "watched"     
  end

  get '/movies/christmas/', to: 'movies#christmas'
  get '/movies/related/:id', to: 'movies#related'
  get '/movies/rt/:id', to: 'movies#rt'
  get '/movies/traileraddict/:id', to: 'movies#traileraddict'

  get 'movies/refresh'
  get 'movies/reddit'
  get 'info/registrations'

  get 'home/trakt'

  # Tests
  get 'home/reddit'
  get 'home/apiRTMovieTest'
  get 'home/apiRTTest'
  get 'home/apitest2'
  get 'home/apitest'

  resources :movies

  # match 'users/sign_up', to: 'info#registrations', via: [:get, :post]

  

  root 'movies#index'

end

app/models/favourite.rb
class Favourite < ActiveRecord::Base
	belongs_to :user
	belongs_to :movie
	validates_uniqueness_of :movie, :scope => :user
end

app/controllers/favourites_controller.rb
class FavouritesController < ApplicationController
  before_filter :authenticate_user!, only: [:create, :destroy]
  before_action :get_user, only: [:index,:show,:edit,:update,:destroy,:new,:create]
  before_action :set_favourite, only: [:show, :edit, :update, :destroy]

  # GET /favourites
  # GET /favourites.json
  def index
    per_page = (params.has_key?(:per_page) && params[:per_page].to_i != 0) ? params[:per_page].to_i : 4
    @favourites  = @user.favourites.joins(:movie).all.page(params[:page]).per_page(per_page)
  end

  # POST /favourites
  # POST /favourites.json
  def create

    if Favourite.exists?(favourite_params)
      respond_to do |format|
          format.json { render json: 'Movie is already on favourite list', status: 304 }
      end
    else
      @favourite = current_user.favourites.new(favourite_params)

      respond_to do |format|
        if @favourite.save
          format.json { render :show, status: :created, location: [current_user,:favourites] }
        else
          format.json { render json: @favourite.errors, status: :unprocessable_entity }
        end
      end
    end

  end

  # DELETE /favourites/1
  # DELETE /favourites/1.json
  def destroy
    @favourite.destroy
    respond_to do |format|
      format.html { redirect_to [current_user,:favourites], notice: 'Favourite was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_favourite
      @favourite = @user.favourites.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def favourite_params
      params.require(:favourite).permit(:movie_id, :user_id)
    end

    def get_user
      @user = User.find(params[:user_id])
    end

end

app/helpers/favourites_helper.rb
module FavouritesHelper
end

app/views/favourites/_form.html.erb
<%= form_for([@user,@favourite],html: {role: "form"}) do |f| %>
  <% if @favourite.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@favourite.errors.count, "error") %> prohibited this favourite from being saved:</h2>

      <ul>
      <% @favourite.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :movie_id %><br>
    <%= f.number_field :movie_id %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.number_field :user_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/favourites/edit.html.erb
<h1>Editing favourite</h1>

<%= render 'form' %>

<%= link_to 'Show', user_favourite_path(@user,@favourite.id) %> |
<%= link_to 'Back', user_favourite_path %>

app/views/favourites/index.html.erb
<ol class="breadcrumb">
  <li class="active">Favourites</li>
</ol>

<div class="row">

   <% @favourites.each do |favourite| %>
    <div class='col-md-12 col-xs-12'>
      <div class='related-movie'>

        <div class='list-group-item row'>
          <div class='col-sm-2 col-xs-12 text-center'>
            <%= image_tag favourite.movie.posterSmallURL, size: '64', class: 'img-responsive' %>
            <small class='visible-xs'><%= truncate(favourite.movie.title, length: 70) %></small>
          </div>

          <div class='col-sm-8 hidden-xs'>
            <h4 class="list-group-item-heading"><%= truncate(favourite.movie.title, length: 40) %></h4>
            <p class="list-group-item-text visible-xs"><%= truncate(favourite.movie.overview, length: 50) %></p>
            <p class="list-group-item-text visible-sm"><%= truncate(favourite.movie.overview, length: 70) %></p>
            <p class="list-group-item-text visible-md"><%= truncate(favourite.movie.overview, length: 120) %></p>
            <p class="list-group-item-text visible-lg"><%= truncate(favourite.movie.overview, length: 160) %></p>
          </div>

          <div class='col-sm-2 hidden-xs'>

            <div class="list-group">

              <%= link_to movie_path(favourite.movie), class: 'list-group-item' do %>
                <span aria-hidden="true" class="glyphicon glyphicon-info-sign"></span> View
              <% end %>

              <%= link_to [@user,favourite], class: 'list-group-item', method: :delete, data: { confirm: 'Are you sure you want to remove this favourite?' } do %>
                <span aria-hidden="true" class="glyphicon glyphicon-remove-sign"></span> Remove
              <% end %>

            </div>

          </div>
        
        </div>

      </div>
    </div>

  <% end %>

</div>

<div class="row text-center">
  <%= will_paginate @movies,previous_label: h("<"), next_label: h(">"), renderer: BootstrapPagination::Rails %>  
</div>

app/views/favourites/new.html.erb
<h1>New favourite</h1>

<%= render 'form' %>

<%= link_to 'Back', user_favourites_path %>

app/views/favourites/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Movie:</strong>
  <%= @favourite.movie_id %>
</p>

<p>
  <strong>User:</strong>
  <%= @favourite.user_id %>
</p>

<%= link_to 'Edit', edit_user_favourite_path(@user.id,@favourite) %> |
<%= link_to 'Back', user_favourites_path %>